"""
iggnition.regions — Structural and functional region annotations for antibody
variable domains, expressed in the Aho coordinate system used by IgNition.

All positions are 1-based.  Two coordinate frames are provided:

  * **Aho AA** – amino acid position in the Aho numbering scheme
    (H: 1–149, K/L: 1–148).
  * **IgNition nt** – the corresponding nucleotide positions as produced by
    ``iggnition.run()``.  The relationship is exact and deterministic::

        nt_start(aho) = (aho - 1) * 3 + 1
        nt_end(aho)   =  aho      * 3

Derivation
----------
CDR/FR boundaries, conserved-residue positions, and insertion-slot locations
were derived directly from the human germline database embedded in IgNition
(``src/core/germline_data.rs``, generated by ``scripts/bootstrap_germlines.py``
from ANARCI's ``number_aho()`` function).

* CDR/FR boundaries: determined by gap patterns across all IGHV/IGKV/IGLV
  germlines — insertion-slot positions (occupied by some germlines, absent in
  others) define the outer edges of each CDR.
* Conserved residues (Cys23, Trp43, Cys106): read directly from
  representative germlines (IGHV1-18*01, IGKV1-12*01, IGLV1-36*01).
* VH ↔ IMGT correspondence at anchor positions:
  – Aho 23 = IMGT 23 (FR1 Cys)
  – Aho 43 = IMGT 41 (FR2 Trp)  → +2 offset post-CDR1
  – Aho 106 = IMGT 104 (FR3 Cys) → +2 offset post-CDR2

References
----------
* Honegger & Plückthun (2001) J Mol Biol 309:657 — Aho numbering scheme.
* Foote & Winter (1992) J Mol Biol 224:487 — Vernier zone.
* Chothia et al. (1989) Nature 342:877; (1992) J Mol Biol 227:799 — canonical
  loop structures.
* Al-Lazikani et al. (1997) J Mol Biol 273:927 — canonical structure analysis.
* Lefranc et al. (2003) Dev Comp Immunol 27:55 — IMGT numbering.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------

def aho_to_nt(aho_pos: int) -> tuple[int, int, int]:
    """Return the three IgNition nt positions for an Aho AA position."""
    base = (aho_pos - 1) * 3
    return base + 1, base + 2, base + 3


def aho_range_to_nt(aho_start: int, aho_end: int) -> tuple[int, int]:
    """Return the (first_nt, last_nt) IgNition nt range for an Aho AA range."""
    return (aho_start - 1) * 3 + 1, aho_end * 3


def region_of(aho_pos: int, chain: str) -> str | None:
    """Return the CDR/FR name for a given Aho position and chain ('H', 'K', or 'L').

    Returns ``None`` if the position is an insertion slot that does not belong
    to any canonical region (this should not occur for standard sequences).
    """
    chain = chain.upper()
    if chain not in CDR_REGIONS:
        raise ValueError(f"Unknown chain '{chain}'. Expected 'H', 'K', or 'L'.")
    for name, (start, end) in CDR_REGIONS[chain].items():
        if start <= aho_pos <= end:
            return name
    return None


# ---------------------------------------------------------------------------
# CDR / FR boundaries
# ---------------------------------------------------------------------------
# Keys: chain ('H', 'K', 'L').
# Values: dict of region_name → (aho_start, aho_end) — 1-based, inclusive.
#
# Boundaries reflect the *full coordinate slot* for each region, including
# insertion positions allocated for longer loops.  An antibody with a short
# CDR will not have residues at every position in the range — the gaps are
# simply scored as '-' by IgNition.
#
# Differences between VH and VK/VL:
#   CDR2 — VH: 50–64 (insertion slots at 62–64, reflecting the longer H2 loop)
#           VK/VL: 50–66 (insertion slots at 59–66, accommodating rare long L2)
#   FR3  — VH starts at 65; VK/VL starts at 67.
#   CDR3 — VH: 109–137, FR4 138–149
#           VK/VL: 109–138, FR4 139–148
#
# Note that positions 85–86 are insertion slots within VK/VL FR3 and are
# normally unoccupied for most human germlines.

CDR_REGIONS: dict[str, dict[str, tuple[int, int]]] = {
    "H": {
        "FR1":  (1,   25),
        "CDR1": (26,  38),   # insertion slots: 28, 34–38
        "FR2":  (39,  49),
        "CDR2": (50,  64),   # insertion slots: 62–64
        "FR3":  (65, 108),
        "CDR3": (109, 137),  # all CDR3 insertion slots; J-gene contributes 138+
        "FR4":  (138, 149),
    },
    "K": {
        "FR1":  (1,   25),
        "CDR1": (26,  38),   # insertion slots: 27–28, 33–38
        "FR2":  (39,  49),
        "CDR2": (50,  66),   # insertion slots: 59–66
        "FR3":  (67, 108),   # insertion slots: 85–86
        "CDR3": (109, 138),
        "FR4":  (139, 148),
    },
    "L": {
        "FR1":  (1,   25),
        "CDR1": (26,  38),   # insertion slots: 28, 34–38
        "FR2":  (39,  49),
        "CDR2": (50,  66),   # insertion slots: 59–66
        "FR3":  (67, 108),   # insertion slots: 85–86
        "CDR3": (109, 138),
        "FR4":  (139, 148),
    },
}

# Pre-computed IgNition nt ranges for each region (first_nt, last_nt)
CDR_REGIONS_NT: dict[str, dict[str, tuple[int, int]]] = {
    chain: {
        region: aho_range_to_nt(start, end)
        for region, (start, end) in regions.items()
    }
    for chain, regions in CDR_REGIONS.items()
}


# ---------------------------------------------------------------------------
# Structural landmarks
# ---------------------------------------------------------------------------
# Landmark positions that are absolutely conserved across human antibody
# variable domains.  All Aho positions are read directly from the embedded
# germline database.

LANDMARKS: dict[str, dict[str, dict]] = {
    "H": {
        # ── Intrachain disulfide bond ──────────────────────────────────────
        "Cys_disulfide_N": {
            "aho": 23,
            "nt":  aho_range_to_nt(23, 23),
            "region": "FR1",
            "note": "N-terminal Cys of the VH intrachain disulfide bond "
                    "(IMGT 23 / Kabat ~22–23).  Absolutely conserved.",
        },
        "Cys_disulfide_C": {
            "aho": 106,
            "nt":  aho_range_to_nt(106, 106),
            "region": "FR3",
            "note": "C-terminal Cys of the VH intrachain disulfide bond "
                    "(IMGT 104 / Kabat 92).  Absolutely conserved.",
        },
        # ── Conserved Trp anchoring FR2 ────────────────────────────────────
        "Trp_FR2": {
            "aho": 43,
            "nt":  aho_range_to_nt(43, 43),
            "region": "FR2",
            "note": "Conserved Trp at the start of FR2 beta-strand "
                    "(IMGT 41 / Kabat 36).  Packs against VL Trp43 at the "
                    "VH–VL interface.",
        },
        # ── VH–VL interface (beta-sheet packing) ──────────────────────────
        # Kabat 37, 39, 44, 45, 47 → approx Aho 44, 46, 51, 52, 54
        "VH_VL_interface": {
            "aho": [44, 46, 51, 52, 54],
            "nt":  [aho_range_to_nt(p, p) for p in [44, 46, 51, 52, 54]],
            "region": "FR2",
            "note": "Key VH–VL packing residues (Kabat 37, 39, 44, 45, 47). "
                    "Ile/Leu/Val at these positions form the hydrophobic core "
                    "of the domain interface.",
        },
        # ── Hydrophobic beta-sheet core (FR1 strand) ──────────────────────
        "hydrophobic_core_FR1": {
            "aho": [4, 5, 11, 20],
            "nt":  [aho_range_to_nt(p, p) for p in [4, 5, 11, 20]],
            "region": "FR1",
            "note": "Leu/Val residues in FR1 that form the hydrophobic beta-sheet "
                    "core (Kabat 4, 5, 11, 20).  Conserved in >95% of human VH.",
        },
    },
    "K": {
        "Cys_disulfide_N": {
            "aho": 23,
            "nt":  aho_range_to_nt(23, 23),
            "region": "FR1",
            "note": "N-terminal Cys of the VL intrachain disulfide bond "
                    "(IMGT 23 / Kabat 23).  Absolutely conserved.",
        },
        "Cys_disulfide_C": {
            "aho": 106,
            "nt":  aho_range_to_nt(106, 106),
            "region": "FR3",
            "note": "C-terminal Cys of the VL intrachain disulfide bond "
                    "(IMGT 104 / Kabat 88).  Absolutely conserved.",
        },
        "Trp_FR2": {
            "aho": 43,
            "nt":  aho_range_to_nt(43, 43),
            "region": "FR2",
            "note": "Conserved Trp at the start of FR2 beta-strand "
                    "(IMGT 41 / Kabat 35).  Packs against VH Trp43 at the "
                    "VH–VL interface.",
        },
        "VH_VL_interface": {
            "aho": [41, 43, 49, 50, 52],
            "nt":  [aho_range_to_nt(p, p) for p in [41, 43, 49, 50, 52]],
            "region": "FR2",
            "note": "Key VH–VL packing residues (Kabat VL 34, 36, 43, 44, 46). "
                    "Complement the VH interface.",
        },
    },
    "L": {
        "Cys_disulfide_N": {
            "aho": 23,
            "nt":  aho_range_to_nt(23, 23),
            "region": "FR1",
            "note": "N-terminal Cys of the VL intrachain disulfide bond "
                    "(IMGT 23).  Absolutely conserved.",
        },
        "Cys_disulfide_C": {
            "aho": 106,
            "nt":  aho_range_to_nt(106, 106),
            "region": "FR3",
            "note": "C-terminal Cys of the VL intrachain disulfide bond "
                    "(IMGT 104).  Absolutely conserved.",
        },
        "Trp_FR2": {
            "aho": 43,
            "nt":  aho_range_to_nt(43, 43),
            "region": "FR2",
            "note": "Conserved Trp at the start of FR2 beta-strand "
                    "(IMGT 41 / Kabat 35).  Packs against VH Trp43 at the "
                    "VH–VL interface.",
        },
        "VH_VL_interface": {
            "aho": [41, 43, 49, 50, 52],
            "nt":  [aho_range_to_nt(p, p) for p in [41, 43, 49, 50, 52]],
            "region": "FR2",
            "note": "Key VH–VL packing residues (Kabat VL 34, 36, 43, 44, 46).",
        },
    },
}


# ---------------------------------------------------------------------------
# Vernier zone
# ---------------------------------------------------------------------------
# Foote & Winter (1992) defined the Vernier zone as framework residues
# immediately underlying the CDR loops that modulate CDR conformation.
#
# Original Kabat positions → approximate Aho equivalents.
# Mapping notes (for human germlines without CDR insertions):
#   FR1        : Aho ≈ Kabat  (no offset; both schemes agree through position 23)
#   CDR1/FR2   : Kabat FR2 start (36) → Aho FR2 start (39); Kabat +3 → Aho offset
#                So FR2 positions: Aho ≈ Kabat + 3
#   FR3        : Kabat FR3 start (66) → Aho FR3 start (65); -1 offset
#                So FR3 positions: Aho ≈ Kabat - 1
#
# ⚠ These mappings are approximate for germlines without CDR insertions.
# Sequences with CDR1 or CDR2 insertions shift the CDR loop positions
# within the Aho coordinate frame; only the framework positions listed here
# are invariant.

VERNIER_ZONE: dict[str, dict[str, int | str]] = {
    "H": {
        # Kabat → Aho for VH Vernier positions
        # FR1 positions (no offset)
        2:  {"aho": 2,   "kabat": 2,  "region": "FR1",
             "note": "FR1 beta-strand; packs against CDR2"},
        # CDR1 positions (CDR1 is roughly 1:1 for positions 26–33)
        27: {"aho": 27,  "kabat": 27, "region": "CDR1",
             "note": "CDR1 loop position influencing CDR1 conformation"},
        29: {"aho": 29,  "kabat": 29, "region": "CDR1",
             "note": "CDR1 position (structurally conserved in canonical CDR1)"},
        30: {"aho": 30,  "kabat": 30, "region": "CDR1",
             "note": "CDR1 canonical position"},
        # FR2 positions (Kabat + 3 ≈ Aho for typical germlines)
        36: {"aho": 43,  "kabat": 36, "region": "FR2",
             "note": "Conserved Trp; central Vernier position"},
        47: {"aho": 54,  "kabat": 47, "region": "FR2",
             "note": "FR2 position packing under CDR2; Ile/Leu/Val"},
        48: {"aho": 55,  "kabat": 48, "region": "FR2",
             "note": "FR2 position packing under CDR2"},
        49: {"aho": 56,  "kabat": 49, "region": "FR2",
             "note": "FR2 position packing under CDR2"},
        # FR3 positions (Kabat − 1 ≈ Aho for typical germlines)
        67: {"aho": 66,  "kabat": 67, "region": "FR3",
             "note": "FR3; packs under CDR2 base"},
        69: {"aho": 68,  "kabat": 69, "region": "FR3",
             "note": "FR3; adjacent to CDR2 stem"},
        71: {"aho": 70,  "kabat": 71, "region": "FR3",
             "note": "FR3 canonical position for CDR1 length determination"},
        78: {"aho": 77,  "kabat": 78, "region": "FR3",
             "note": "FR3; packed core residue"},
        93: {"aho": 92,  "kabat": 93, "region": "FR3",
             "note": "FR3; packs under CDR3 base"},
        94: {"aho": 93,  "kabat": 94, "region": "FR3",
             "note": "FR3; packs under CDR3 base"},
    },
    "L": {
        # VL Vernier zone (Foote & Winter; Kabat VL numbering)
        # FR1 (no offset)
        2:  {"aho": 2,   "kabat_vl": 2,  "region": "FR1",
             "note": "FR1 beta-strand"},
        # CDR1 positions (approximately 1:1)
        25: {"aho": 25,  "kabat_vl": 25, "region": "CDR1",
             "note": "CDR1 loop position"},
        26: {"aho": 26,  "kabat_vl": 26, "region": "CDR1",
             "note": "CDR1 first position"},
        27: {"aho": 27,  "kabat_vl": 27, "region": "CDR1",
             "note": "CDR1 position"},
        29: {"aho": 29,  "kabat_vl": 29, "region": "CDR1",
             "note": "CDR1 canonical position"},
        33: {"aho": 33,  "kabat_vl": 33, "region": "CDR1",
             "note": "CDR1 last conserved position"},
        # FR2 positions (Kabat VL + 3 ≈ Aho, analogous to VH FR2)
        46: {"aho": 49,  "kabat_vl": 46, "region": "FR2",
             "note": "FR2 position packing under CDR2"},
        48: {"aho": 51,  "kabat_vl": 48, "region": "FR2",
             "note": "FR2 packing position"},
        49: {"aho": 52,  "kabat_vl": 49, "region": "FR2",
             "note": "FR2 packing position"},
        # FR3 positions (Kabat VL − 1 ≈ Aho, analogous to VH)
        64: {"aho": 73,  "kabat_vl": 64, "region": "FR3",
             "note": "FR3; packs under CDR2"},
        68: {"aho": 77,  "kabat_vl": 68, "region": "FR3",
             "note": "FR3 core packing"},
        69: {"aho": 78,  "kabat_vl": 69, "region": "FR3",
             "note": "FR3 packing residue"},
        71: {"aho": 80,  "kabat_vl": 71, "region": "FR3",
             "note": "FR3 canonical position for CDR1 length (VL analogue of VH71)"},
    },
}

# Convenience: Aho positions only (useful for masking / selection in DataFrames)
VERNIER_ZONE_AHO: dict[str, list[int]] = {
    chain: [v["aho"] for v in positions.values()]
    for chain, positions in VERNIER_ZONE.items()
}


# ---------------------------------------------------------------------------
# Chothia canonical structural positions
# ---------------------------------------------------------------------------
# Chothia et al. defined "canonical structures" for CDR loops: a small set
# of key positions (in CDR and adjacent FR) whose identities determine the
# backbone conformation of the loop.
#
# These are expressed in Kabat numbering in the original papers.
# Aho equivalents use the same offsets as the Vernier zone above.
#
# Sources:
#   Chothia et al. (1989) Nature 342:877 (H1, H2, L1, L2, L3 initial set)
#   Chothia et al. (1992) J Mol Biol 227:799 (extended set)
#   Al-Lazikani et al. (1997) J Mol Biol 273:927 (comprehensive analysis)
#
# ⚠ CDR3 is not listed here — H3 and L3 conformations are determined by
# length and sequence in a way that is not captured by a fixed set of
# canonical positions.

CHOTHIA_CANONICAL: dict[str, dict[str, list[dict]]] = {
    "H": {
        "CDR1_H1": [
            {"kabat": 24, "aho": 24, "note": "FR1 position adjacent to CDR1; Ala/Gly"},
            {"kabat": 26, "aho": 26, "note": "First CDR1 residue"},
            {"kabat": 27, "aho": 27, "note": "CDR1; key length determinant"},
            {"kabat": 29, "aho": 29, "note": "CDR1; Ile/Val highly conserved in H1"},
            {"kabat": 34, "aho": 33, "note": "CDR1 canonical closing residue"},
            {"kabat": 94, "aho": 93, "note": "FR3; distal canonical position for H1 conformation"},
        ],
        "CDR2_H2": [
            {"kabat": 52, "aho": 59, "note": "CDR2; Gly/Ser in some canonical forms"},
            {"kabat": 55, "aho": 62, "note": "CDR2; key backbone position"},
            {"kabat": 71, "aho": 70, "note": "FR3 canonical position for H2 length"},
        ],
    },
    "L": {
        "CDR1_L1": [
            {"kabat_vl": 29, "aho": 29, "note": "CDR1; critical length determinant"},
            {"kabat_vl": 33, "aho": 33, "note": "CDR1; canonical closing position"},
            {"kabat_vl": 71, "aho": 80, "note": "FR3; canonical position for L1 conformation"},
            {"kabat_vl": 90, "aho": 99, "note": "FR3 end; backbone position"},
            {"kabat_vl": 95, "aho": 104, "note": "CDR3 start; affects L1 conformation"},
        ],
        "CDR2_L2": [
            {"kabat_vl": 48, "aho": 51, "note": "CDR2; highly conserved"},
            {"kabat_vl": 51, "aho": 54, "note": "CDR2; backbone determinant"},
            {"kabat_vl": 52, "aho": 55, "note": "CDR2"},
        ],
        "CDR3_L3": [
            {"kabat_vl": 90, "aho": 99,  "note": "CDR3; length-determining position"},
            {"kabat_vl": 95, "aho": 104, "note": "CDR3; determines closure"},
            {"kabat_vl": 97, "aho": 106, "note": "CDR3 closing position; often Pro"},
        ],
    },
}


# ---------------------------------------------------------------------------
# Key numbering-scheme cross-reference table
# ---------------------------------------------------------------------------
# Verified anchor points between Aho, IMGT, and Kabat numbering schemes for
# human antibody variable domains.
#
# Rule of thumb derived from these anchors (no CDR insertions):
#   FR1         : Aho ≈ IMGT ≈ Kabat  (identical through position 23)
#   Post-CDR1   : Aho = IMGT + 2  (Aho CDR1 starts 1 earlier, has 1 more slot)
#   Post-CDR2   : Aho = IMGT + 2  (offset preserved across CDR2)
#   FR3 vs Kabat: Aho ≈ Kabat − 1  (Kabat CDR2 is 1 longer than Aho CDR2)
#
# Note: sequences with CDR insertions will have additional offsets inside
# the CDR regions.  The framework positions above are invariant.

NUMBERING_CROSSREF: dict[str, list[dict]] = {
    "H": [
        {"aho": 1,   "imgt": 1,   "kabat_h": 1,   "residue": "Gln/Glu FR1 start"},
        {"aho": 23,  "imgt": 23,  "kabat_h": 22,  "residue": "Cys (intrachain SS, N-terminal)"},
        {"aho": 26,  "imgt": 27,  "kabat_h": 26,  "residue": "CDR1 start"},
        {"aho": 43,  "imgt": 41,  "kabat_h": 36,  "residue": "Trp FR2 (absolutely conserved)"},
        {"aho": 50,  "imgt": 50,  "kabat_h": 50,  "residue": "CDR2 start"},
        {"aho": 65,  "imgt": 66,  "kabat_h": 66,  "residue": "FR3 start"},
        {"aho": 106, "imgt": 104, "kabat_h": 92,  "residue": "Cys (intrachain SS, C-terminal)"},
        {"aho": 109, "imgt": 105, "kabat_h": 95,  "residue": "CDR3 start"},
        {"aho": 138, "imgt": 118, "kabat_h": 103, "residue": "FR4 start / J-gene Trp"},
        {"aho": 149, "imgt": 128, "kabat_h": 113, "residue": "VH domain end"},
    ],
    "L": [
        {"aho": 1,   "imgt": 1,   "kabat_l": 1,   "residue": "Asp/Glu FR1 start"},
        {"aho": 23,  "imgt": 23,  "kabat_l": 23,  "residue": "Cys (intrachain SS, N-terminal)"},
        {"aho": 26,  "imgt": 27,  "kabat_l": 24,  "residue": "CDR1 start"},
        {"aho": 43,  "imgt": 41,  "kabat_l": 35,  "residue": "Trp FR2 (absolutely conserved)"},
        {"aho": 50,  "imgt": 50,  "kabat_l": 50,  "residue": "CDR2 start"},
        {"aho": 67,  "imgt": 66,  "kabat_l": 57,  "residue": "FR3 start (VL; after wider CDR2 slot)"},
        {"aho": 106, "imgt": 104, "kabat_l": 88,  "residue": "Cys (intrachain SS, C-terminal)"},
        {"aho": 109, "imgt": 105, "kabat_l": 89,  "residue": "CDR3 start"},
        {"aho": 139, "imgt": 118, "kabat_l": 98,  "residue": "FR4 start"},
        {"aho": 148, "imgt": 127, "kabat_l": 107, "residue": "VL domain end"},
    ],
}


# ---------------------------------------------------------------------------
# IgNition-specific position labels (for ML feature construction)
# ---------------------------------------------------------------------------
# Pre-built column-name → (aho_pos, codon_pos) mappings that correspond
# exactly to the wide-format output columns H1…H447 and L1…L444.
#
# Example: column "H1"  → Aho AA position 1, codon position 1
#          column "H3"  → Aho AA position 1, codon position 3
#          column "H4"  → Aho AA position 2, codon position 1
#
# These can be used to build per-position feature DataFrames, apply CDR masks,
# or label training data.

def nt_col_to_aho(col_name: str) -> tuple[int, int]:
    """Convert a wide-format column name ('H42', 'L123') to (aho_pos, codon_pos).

    Returns (aho_position, codon_position) where codon_position ∈ {1, 2, 3}.

    Example::

        nt_col_to_aho("H1")   # → (1, 1)
        nt_col_to_aho("H3")   # → (1, 3)
        nt_col_to_aho("H4")   # → (2, 1)
        nt_col_to_aho("L444") # → (148, 3)
    """
    nt_idx = int(col_name[1:])          # 1-based nt position
    aho_pos = (nt_idx - 1) // 3 + 1    # 1-based Aho AA position
    codon_pos = (nt_idx - 1) % 3 + 1   # 1, 2, or 3
    return aho_pos, codon_pos


def cdr_mask(chain: str, region: str, chain_prefix: str | None = None) -> list[str]:
    """Return the list of IgNition wide-format column names in a CDR/FR region.

    Parameters
    ----------
    chain : str
        ``'H'``, ``'K'``, or ``'L'``.
    region : str
        One of ``'FR1'``, ``'CDR1'``, ``'FR2'``, ``'CDR2'``, ``'FR3'``,
        ``'CDR3'``, ``'FR4'``.
    chain_prefix : str, optional
        Column prefix to use.  Defaults to ``'H'`` for heavy and ``'L'`` for
        kappa/lambda.  (In the wide-format output, both K and L chains use the
        ``L`` prefix.)

    Returns
    -------
    list[str]
        Column names, e.g. ``['H76', 'H77', ..., 'H114']`` for VH CDR1.

    Example::

        cdr_mask("H", "CDR1")    # → ['H76', 'H77', ..., 'H114']
        cdr_mask("L", "CDR3")    # → ['L325', 'L326', ..., 'L414']
    """
    chain = chain.upper()
    if chain not in CDR_REGIONS:
        raise ValueError(f"Unknown chain '{chain}'.")
    aho_start, aho_end = CDR_REGIONS[chain][region]
    nt_start, nt_end = aho_range_to_nt(aho_start, aho_end)
    if chain_prefix is None:
        chain_prefix = "H" if chain == "H" else "L"
    return [f"{chain_prefix}{i}" for i in range(nt_start, nt_end + 1)]
