#!/usr/bin/env python3
"""
Bootstrap script: extract human V/J germlines from ANARCI,
apply Aho numbering via direct state-vector construction (no HMMER needed),
and emit a Rust source file embedding the germline database.

Run once:
    python3 scripts/bootstrap_germlines.py > src/core/germline_data.rs
"""

import sys
from anarci.germlines import all_germlines
from anarci.schemes import number_aho


def build_state_vector(aligned_seq: str):
    """Convert a pre-aligned 128-char germline string to an ANARCI state_vector."""
    sequence = aligned_seq.replace("-", "")
    state_vector = []
    si = 0
    for state_id, aa in enumerate(aligned_seq, start=1):
        if aa == "-":
            state_vector.append(((state_id, "d"), None))
        else:
            state_vector.append(((state_id, "m"), si))
            si += 1
    return sequence, state_vector


def aho_number_germline(aligned_seq: str, chain_char: str):
    """Return list of (aho_position, insertion_code, amino_acid) for a germline.
    Skips gap positions ('-').
    insertion_code is ' ' for main positions, a letter (A/B/...) for insertions.
    """
    sequence, state_vector = build_state_vector(aligned_seq)
    if not sequence:
        return []
    numbering, _start, _end = number_aho(state_vector, sequence, chain_char)
    # numbering is list of ((pos, ins_code), aa)
    positions = []
    for (pos, ins_code), aa in numbering:
        if aa == "-":
            continue  # unoccupied Aho position for this germline
        positions.append((int(pos), ins_code.strip(), aa))
    return positions


def format_positions_rust(positions):
    """Format a list of (aho_pos, ins_code, aa) as a Rust &[(u16, u8, u8)] literal."""
    parts = []
    for aho_pos, ins_code, aa in positions:
        ins_byte = ord(ins_code) if ins_code else 0
        aa_byte = ord(aa)
        parts.append(f"({aho_pos}u16, {ins_byte}u8, {aa_byte}u8)")
    return "&[" + ", ".join(parts) + "]"


def escape_rust_str(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main():
    # chain_char → (rust ChainType variant, GeneType)
    chain_map = {
        "H": "ChainType::Heavy",
        "K": "ChainType::Kappa",
        "L": "ChainType::Lambda",
    }

    gene_types = {
        "V": "GeneType::V",
        "J": "GeneType::J",
    }

    lines = []
    lines.append("// AUTO-GENERATED by scripts/bootstrap_germlines.py — DO NOT EDIT")
    lines.append("// Human V and J germlines with Aho numbering, embedded at compile time.")
    lines.append("")
    lines.append("use crate::core::types::{ChainType, GeneType};")
    lines.append("")
    lines.append("/// A single residue in the Aho-numbered germline.")
    lines.append("/// (aho_position, insertion_code [0 = none], amino_acid)")
    lines.append("pub type GermlineResidue = (u16, u8, u8);")
    lines.append("")
    lines.append("/// A germline gene entry.")
    lines.append("pub struct GermlineEntry {")
    lines.append('    pub id: &\'static str,')
    lines.append("    pub chain: ChainType,")
    lines.append("    pub gene: GeneType,")
    lines.append("    /// Occupied Aho positions: (aho_pos, ins_code, aa_byte)")
    lines.append("    pub residues: &'static [GermlineResidue],")
    lines.append("}")
    lines.append("")
    lines.append("pub static GERMLINES: &[GermlineEntry] = &[")

    total = 0
    errors = 0

    for gene_type_str, gene_rust in gene_types.items():
        gene_data = all_germlines.get(gene_type_str, {})
        for chain_char, chain_rust in chain_map.items():
            chain_data = gene_data.get(chain_char, {})
            human_data = chain_data.get("human", {})
            for germline_id, aligned_seq in human_data.items():
                try:
                    positions = aho_number_germline(aligned_seq, chain_char)
                    if not positions:
                        print(
                            f"WARNING: empty positions for {germline_id}", file=sys.stderr
                        )
                        errors += 1
                        continue
                    pos_str = format_positions_rust(positions)
                    lines.append("    GermlineEntry {")
                    lines.append(f'        id: "{escape_rust_str(germline_id)}",')
                    lines.append(f"        chain: {chain_rust},")
                    lines.append(f"        gene: {gene_rust},")
                    lines.append(f"        residues: {pos_str},")
                    lines.append("    },")
                    total += 1
                except Exception as e:
                    print(
                        f"ERROR numbering {germline_id}: {e}", file=sys.stderr
                    )
                    errors += 1

    lines.append("];")
    lines.append("")
    lines.append(f"// Total germlines embedded: {total} (errors: {errors})")

    print("\n".join(lines))
    print(f"Bootstrap complete: {total} germlines, {errors} errors", file=sys.stderr)


if __name__ == "__main__":
    main()
